name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04  # 🔄 Оновлено з ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # ✅ Виправлено з chekout

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker compose build --build-arg DEV=true  # ✅ Додано, щоб flake8 точно встановився

      - name: Run tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run linting
        run: docker compose run --rm app sh -c "flake8"
